### PR TITLE
Auto-discover path to Elm tools and the `elm.json` file when opening a project for the first time

### PR DESCRIPTION
**Pull request by klazuka**
This should be a nice usability win.

- auto-discovers the Elm compiler, elm-format and elm-test (prioritizing tools installed in local `node_modules` over global install)
- auto-attaches the first `elm.json` file it finds (breadth-first search from the content root to a max depth of 3)

### CODE REVIEW

**Comment by pravdomil** [comment]
does not work for me?

image

**Comment by klazuka** [comment]
@pravdomil what version/flavor of IntelliJ are you using?

How did you create the project?

**Comment by pravdomil** [comment]
```
IntelliJ IDEA 2020.1.2
IntelliJ Elm 4.1.0
```
```sh
mkdir foo
cd foo
elm init
touch src/Main.elm
idea .
```

**Comment by klazuka** [comment]
The problem is that you're opening an individual source file instead of a directory. I have the same configuration as you, but if instead of `idea src/Main.elm` you instead do `idea .` it works.

Launching IntelliJ on an individual source file appears to load it in a lightweight mode without project view, etc.

**Comment by pravdomil** [comment]
oh sorry I edited the comment, I open the whole project, not a single file, see screenshot

**Comment by pravdomil** [comment]
I'm on macOS 10.13.3.

**Comment by klazuka** [comment]
Are you saying that on macOS 10.13.3 when you open the `foo` directory in IntelliJ (either from CLI or GUI) it doesn't automatically attach the `elm.json` file?

**Comment by pravdomil** [comment]
It does not, tried many times.

**Comment by klazuka** [comment]
I followed up with you on the Elm Slack. Let's take it from there.

**Pull request merged**
