### PR TITLE
Clojj/fix color null

### PR DESCRIPTION
**Pull request by clojj**
some markup-chunk have 'null' color (which is a strange enough JSON output from Elm)

### CODE REVIEW

**Comment by clojj** [comment]
how you can produce the message, containing a color=null chunk, this is after my fix

color-null-fixed

**Comment by klazuka** [comment]
That is weird. I couldn’t believe it when I saw it in one of your test fixtures, and I was unable to reproduce it. In any case, thanks!

**Comment by clojj** [comment]
@klazuka 
so did you fix it already ? I can't find a commit for this...

**Comment by klazuka** [comment]
Yes. I forgot to push last night before bed.

**Pull request closed without merging**
