### PR TITLE
mention add missing case braches feature

### PR DESCRIPTION
**Pull request by pravdomil**

### CODE REVIEW

**Comment by klazuka** [comment]
Thanks, but this would need to be like the other features where there is a separate Markdown document which describes the feature in more detail along with screenshots.

**Comment by pravdomil** [comment]
I know, but this is better then not mention it at all

**Comment by pravdomil** [comment]
its better to do not mention at all?

**Comment by klazuka** [comment]
Yes. I'm trying to make sure that any feature which I talk about in the README has supporting documentation/screenshot(s).

**Pull request closed without merging**
