### PR TITLE
Support main functions returning Html.Html in build action

### PR DESCRIPTION
**Pull request by ajalt**
Even when the body of an alias is unresolved, as is the case with `Html.Html`, we still set the alias info on the `TyUnknown`, so we can use that to check the type.

### CODE REVIEW

**Comment by ajalt** [comment]
Note that I'm not able to test this, since the action fails on my Windows machine with `Could not Elm project`  before getting to the type check, but I'm pretty sure this will work.

**Comment by klazuka** [comment]
I had thought about special-casing this, but it seemed brittle just having this hanging out here.

Maybe we could handle this the same way we might handle the implicit, built-in types in 0.18: consolidate the logic for determining if it's a special type in the type inference code. That way if we ever fix it, it will be less likely to be overlooked.

**Comment by klazuka** [comment]
Also, line 62 in `ElmBuildAction` has an error message that says that `Html` type is not supported. So if we remove this limitation, then the error message should also be adjusted.

**Comment by ajalt** [comment]
1. It's up to you; feel free to close this PR if you don't like the approach. I agree that it's not ideal, but this is the first place I've seen that's looking specifically for one of these types. I think there are a lot of aliases to unresolved types, and I didn't want to try to come up with a comprehensive list. The alias info on `TyUnknown` works consistently, and I use it in the documentation provider.

2. I believe I already updated the error message. Did I miss one?

**Comment by klazuka** [comment]
I was wrong about the error message: you already fixed it. You are too good at this stuff! 😄

**Pull request merged**
