### PR TITLE
Bug-fix: properly refactor pipeline branch

### PR DESCRIPTION
**Pull request by ishmum123**

### CODE REVIEW

**Comment by klazuka** [comment]
@ishmum123 can you write a description of the change? I took a quick look at the diff, but I don't see any functional change.

**Comment by ishmum123** [comment]
> @ishmum123 can you write a description of the change? I took a quick look at the diff, but I don't see any functional change.

I am very sorry, I completely forgot to provide the description. 

## Before
https://user-images.githubusercontent.com/9882721/105523314-717bea80-5d08-11eb-979f-78d0101aeffe.mov

## After
https://user-images.githubusercontent.com/9882721/105523583-bd2e9400-5d08-11eb-946a-db00bcde2b23.mov

**Comment by ishmum123** [comment]
@klazuka please let me know if you have any feedback

**Review by klazuka — APPROVED** [review]
Thanks! This is a nice fix.

**Comment by ishmum123** [comment]
@klazuka I am quite interested in this project, if you could point me to the top 3 priorities ATM, I would love to help out

**Comment by pravdomil** [comment]
https://github.com/klazuka/intellij-elm/issues/47
this one is quite common, moving files in/out of a directory

**Comment by ishmum123** [comment]
@pravdomil thanks a lot

**Pull request merged**
